---

- name: RabbitMQ env configuration
  template: >
    src=rabbitmq-env.conf.j2
    dest=/etc/rabbitmq/rabbitmq-env.conf
  when: elao_rabbitmq_env_vars is defined
  sudo: yes

- name: RabbitMQ configuration
  template: >
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
  sudo: yes

- shell: "rabbitmqctl list_vhosts"
  register: cmd_result
  sudo: yes

- name: "Setting vhosts to enable"
  set_fact:
    elao_rabbitmq_vhosts_enabled: "{{ elao_rabbitmq_vhosts|difference(cmd_result.stdout_lines) }}"

- name: "Setting vhosts to disable"
  set_fact:
    elao_rabbitmq_vhosts_disabled: "{{ cmd_result.stdout_lines|difference(elao_rabbitmq_vhosts) }}"

- name: Deleting no more defined vhosts
  shell: "rabbitmqctl delete_vhost {{ item }}"
  with_items: elao_rabbitmq_vhosts_disabled
  when: item != "Listing vhosts ..."
  sudo: yes

- name: Creating missing vhosts
  shell: "rabbitmqctl add_vhost {{ item }}"
  with_items: elao_rabbitmq_vhosts_enabled
  sudo: yes
